### PR TITLE
Ticket # 11 - Delete A Category

### PR DESCRIPTION
**Pull request by cresuta**
# Description

As an admin, this feature will provide them an option to be able to delete a category so that they can remove any that are not needed. When the user clicks on the delete button for the category from the categories list, they will be presented with an extra layer of preventative measure that double checks/confirms if they are sure they want to delete this specific category. If they confirm, then clicking the delete button will remove that category from the database and redirect them back to the list of categories. If they do not confirm, the admin can simply click the link that says "back to list" which will redirect them back to the list of categories. 

Currently, both Edit and Details links for each category are not working have no implementation yet. This will be addressed in a future ticket. 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions

1) Run the command "git fetch --all" to pull down this new branch locally
2) Run the command "git checkout cr-ticket11" to switch over to this branch for viewing/testing
3) Go ahead and log in as an admin with the email admin@example.com
4) Navigate over to the "Category Management" link in the navbar, and please create a few new categories to add to the list of categories by clicking "Create Category". This will help with testing the delete functionality. Examples of category names for this could be "Category Test A", "Category Test B", etc...
5) After creating those test categories, choose one of those from the list and click the "Delete" link. From here, you can test to see that the final delete button works and removes it from both the SQL database and from the list of categories. While you're here, you can also test the "Back to List" link to see that it redirects back to the list of categories.
6) Please run this SQL query to validate that deleting the category(s) did in fact remove their respective records from the category database table. Simply compare this sql query result table to what is displayed on the browser for the list of categories:

select *
from Category;

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Jordan-Twyman** [comment]
Works like a charm but I don't see Aki's My Post navigation link. Can you make sure you pulled main?

**Review by Jordan-Twyman — APPROVED** [review]
### APPROVED

**Comment by sarahebrooks12** [comment]
👼

**Review by mtgoat — APPROVED** [review]
No issues found

**Comment by heavenburdette1988** [comment]
Nicely Done!  Approved!

**Pull request merged**
