### PR TITLE
Hb create tag tkt14

### PR DESCRIPTION
**Pull request by heavenburdette1988**
# Description

An admin user should be able to see and click on the Tag Management link in the menu to get the list of tags. 
The user will see a list of tags that are in alphabetical order.  
There are create, edit, details and delete options.  These edit and details options will not work at this time.
The user can click the create tag button which should send them to a form to enter the new tag name.
When the user enters the tag name and clicks the save  button
The new tag name is added and saved to the database. 
The user should be redirected back to the list where they see the new tag added. 

I added a  addTag Method to the tag repositories and created a view for the create method.

There are no permissions for this ticket but will be included in future tickets.  Assume all users are admins. 

Related Ticket(s):
[https://trello.com/c/JWFbOjrQ]

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions

1. After verifying that you have our repo cloned down into a local repository, `git fetch -a` in the main branch to retrieve the named` hb-createTagTkt14 `that I have pushed up
2. In Terminal `git checkout hb-createTagTkt14` to switch to my branch and in the terminal type `Start TabloidMVC.sln` to open in Visual Studios 2022. 
3. If you have not seeded your database with this data, seed your data  from SQLQuery link :[ https://github.com/NewForce-Cohort-5/tabloidmvc-the-spaghetti-squad/tree/main/SQL]( https://github.com/NewForce-Cohort-5/tabloidmvc-the-spaghetti-squad/tree/main/SQL)
4. 
5. You will need to create the table first and then add the seed data. Choose files in the following order:
     -[01_TabloidMVC_Create_DB.sql](https://github.com/NewForce-Cohort-5/tabloidmvc-the-spaghetti-squad/blob/main/SQL/01_TabloidMVC_Create_DB.sql)
     -[02_TabloidMVC_Seed_Data.sql](https://github.com/NewForce-Cohort-5/tabloidmvc-the-spaghetti-squad/blob/main/SQL/02_TabloidMVC_Seed_Data.sql)
8. Now that you have your seed data, we can test.
9. Click the solid green play button and you will arrive at the home page. You will need to login as [admin@example.com](mailto:admin@example.com).
10. Next go to Tag Management in the menu. This is where you can see the list of tags in alphabetical order and the create new option.  
11. Please test at least 2 times by clicking the create new link and following below instructions.
12. You will be directed to a form to add a new tag name. 
13. Add name and click save.
14. You will be directed back to the updated list where you will see you new tag added. 

 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by Jordan-Twyman — APPROVED** [review]
Works like a charm!

**Comment by Jordan-Twyman** [comment]
You will need to pull the new main and re  commit before we complete this merge @heavenburdette1988

**Review by mtgoat — APPROVED** [review]
Please see the Jordan's comment on updating your branch before merging

**Review by cresuta — APPROVED** [review]
Just need to pull down the new main after the last merged PR and merge back into this branch (your branch is missing the post management link in the navbar). Otherwise, great job! What a refreshing feeling of creating a new tag 😃

**Comment by sarahebrooks12** [comment]
👼

**Comment by heavenburdette1988** [comment]
Updated

**Pull request merged**
