### PR TITLE
HB Ticket 13 view tags

### PR DESCRIPTION
**Pull request by heavenburdette1988**
# Description

An admin user should be able to see and click on the Tag Management link in the menu to get the list of tags. 
The user will see a list of tags that are in alphabetical order.  
There are create, edit, and delete options.  These options will not work at this time. 

I created a Tag Model, TagRepostiory,  ITagRepository, TagController and a View for Index to be able to print the list of tags on the page. 

In addition,  I added a Tag Management link in the menu to give the user access to the tags.  

There are no permissions for this ticket but will be included in future tickets.  Assume all users are admins. 

Related Ticket(s):
[](https://trello.com/c/6B8KtMwy)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions

1. After verifying that you have our repo cloned down into a local repository,` git fetch -a ` in the main branch to retrieve the named hb-tkt13ViewTags that I have pushed up
2. In Terminal `git checkout hb-tkt13ViewTags` to switch to my branch and in the terminal type `Start TabloidMVC.sln` to open in Visual Studios 2022. 
3. If you have not seeded your database with this data, seed your data  from SQLQuery link : [](https://github.com/NewForce-Cohort-5/tabloidmvc-the-spaghetti-squad/tree/main/SQL)
4. You will need to create the table first and then add the seed data. Choose files in the following order:
5. [01_TabloidMVC_Create_DB.sql](https://github.com/NewForce-Cohort-5/tabloidmvc-the-spaghetti-squad/blob/main/SQL/01_TabloidMVC_Create_DB.sql)
6. [02_TabloidMVC_Seed_Data.sql](https://github.com/NewForce-Cohort-5/tabloidmvc-the-spaghetti-squad/blob/main/SQL/02_TabloidMVC_Seed_Data.sql)
7. Now that you have your seed data, we can test.
8.  Click the solid green debugger play button and you will arrive at the home page. You will need to login as admin@example.com.
9. Next go to Tag Management in the menu. This is where you can see the list of tags in the following alphabetical order:

- C#
- Cyclopean Terrors
- Family
- JavaScript

11. Please test at least 3 times by switching between menu items links and logging in and out. 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sarahebrooks12** [comment]
Want to make sure that when we utilize the play button, we are always using the debugger option in testing. Never want to run code without it.

**Comment by sarahebrooks12** [comment]
Please include either a list of all the tags in alphabetical order or a SQL query that would show them in alphabetical order just as you would see them on your browser

**Comment by heavenburdette1988** [comment]
@sarahebrooks12 Thanks! I have corrected it.

**Comment by sarahebrooks12** [comment]
👼

**Comment by Jordan-Twyman** [comment]
Looks good

**Comment by mtgoat** [comment]
No issue found

**Comment by cresuta** [comment]
No issues found. Great job!

**Pull request merged**
